source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'arel', '2.0.2'
gem 'mysql2', '0.2.8'
gem 'rake', '~> 0.8.7'
gem 'rack', '~> 1.2.3'

gem 'devise', '1.1.5'
gem 'inherited_resources'
gem 'simple_form'
gem 'has_scope'
gem 'will_paginate'
gem 'escape_utils'
gem 'meta_where'
gem 'jquery-rails'
gem 'rails_admin', :git => 'git@github.com:scottwainstock/rails_admin.git'
gem 'declarative_authorization'
gem 'haml'
gem 'haml-rails'
gem 'carrierwave'
gem 'mini_magick'
gem 'remotipart'
gem 'pony'
gem 'recaptcha', :require => 'recaptcha/rails'
gem 'newrelic_rpm'
gem 'capistrano'
gem 'geocoder'
gem 'exception_notification_rails3', :require => 'exception_notifier'

group :development, :test do
  gem 'capybara', '0.4.1.1'
  gem 'database_cleaner'
  gem 'gherkin', '2.3.3'
  gem 'cucumber-rails', '0.3.2'
  gem 'cucumber', '0.10.0'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'spork'
  gem 'launchy'
  gem 'autotest'
  gem 'autotest-rails'
  gem 'autotest-growl'
  gem 'ruby-growl'
  gem 'factory_girl', '1.3.3'
  gem 'factory_girl_rails', '1.0.1'
  gem 'pickle', '0.4.4'
  gem 'selenium', '0.0.3'
  gem 'selenium-client', '1.2.18'
  gem 'selenium-webdriver', '0.1.2'
  gem 'cucumber_factory', '1.7.4'
  gem 'fuubar'
  gem 'timecop', '0.3.5'
  gem 'bullet'
  gem 'email_spec'
end
