source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'arel'
gem 'mysql2'
gem 'rake', '~> 0.8.7'

gem 'devise'
gem 'inherited_resources'
gem 'simple_form'
gem 'has_scope'
gem 'will_paginate'
gem 'escape_utils'
gem 'meta_where'
gem 'jquery-rails'
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git', :ref => '840ae353d2d9ca276d87'
gem 'declarative_authorization'
gem 'haml'
gem 'haml-rails'
gem 'carrierwave'
gem 'mini_magick'
gem 'remotipart'
gem 'pony'
gem 'recaptcha', :require => 'recaptcha/rails'
gem 'newrelic_rpm'
gem 'capistrano'

group :development, :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'spork'
  gem 'launchy'
  gem 'autotest'
  gem 'autotest-rails'
  gem 'autotest-growl'
  gem 'ruby-growl'
  gem 'factory_girl'
  gem 'factory_girl_rails'
  gem 'pickle'
  gem 'selenium'
  gem 'selenium-client'
  gem 'cucumber_factory'
  gem 'fuubar'
  gem 'timecop'
  gem 'bullet'
  gem 'email_spec'
end
