source 'http://rubygems.org'

gem 'rails', '3.2.11'
gem 'arel'
gem 'pg'
gem 'rake'
gem 'rack'

gem 'puma'

gem 'paperclip', '3.4.1'
gem 'devise'
gem 'devise-encryptable'
gem 'inherited_resources'
gem 'simple_form'
gem 'has_scope'
gem 'kaminari'
gem 'escape_utils'
gem 'jquery-rails'
gem 'rails_admin'
gem "cancan"
gem 'declarative_authorization'
gem 'haml'
gem 'haml-rails'
gem 'mini_magick'
gem 'remotipart'
gem 'pony'
gem 'recaptcha', :require => 'recaptcha/rails'
gem 'newrelic_rpm'
gem 'capistrano'
gem 'geocoder'
gem 'exception_notification_rails3', :require => 'exception_notifier'
gem 'aws-sdk'
gem 'newrelic_rpm'
gem 'dalli'
gem 'memcachier'
gem 'jquery-ui-rails'
gem 'jbuilder'
gem 'rakismet'
gem 'twitter'
gem 'rails_autolink'

group :test do
  gem 'cucumber-rails', :require => false
  gem 'rspec'
  gem 'rspec-rails'
  gem 'spork'
  gem 'factory_girl'
  gem 'factory_girl_rails', :require => false
  gem 'cucumber_factory'
  gem 'cucumber'
  gem 'launchy'
  gem 'capybara'
  gem 'autotest'
  gem 'autotest-rails'
  gem 'selenium'
  gem 'selenium-client'
  gem "selenium-webdriver", "~> 2.33.0"
  gem 'autotest-growl'
  gem 'timecop'
end

group :development, :test do
  gem 'database_cleaner'
  gem 'gherkin'
  gem 'ruby-growl'
  gem 'pickle'
  gem 'bullet'
  gem 'email_spec'
end
